[package]
name = "lupusreginaÎ²"
version = "0.3.6"
authors = ["Ken Swenson <flat@esoteric.moe>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
chrono = "0.4.6"
directories = "~1.0"
env_logger = "~0.6"
log = "~0.4"
kankyo = {git = "https://github.com/rusty-crates/kankyo"}
rust-ini = "0.13"
rusqlite = "0.18"
typemap = "~0.3"
rand = "0.6"
failure = "0.1"
tempfile = "3"
graphql_client = "0.8"
serde = "1.0"
lazy_static = "1.3"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
#path = "../serenity"
features = ["voice", "framework", "standard_framework"]

[dependencies.reqwest]
version = "0.9"
default-features = false
features = ["rustls-tls"]
