[package]
name = "lupusreginaÎ²"
version = "0.1.0"
authors = ["Ken Swenson <flat@esoteric.moe>"]

[dependencies]
env_logger = "~0.5"
log = "~0.4"
kankyo = "~0.2"

[dependencies.serenity]
version = "0.5"
features = ["voice"]