[package]
name = "lupusreginaÎ²"
version = "0.4.11"
authors = ["Ken Swenson <flat@esoteric.moe>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.12.0"
chrono = "0.4"
directories = "~2.0"
pretty_env_logger = "~0.4"
log = "~0.4"
dotenv = "~0.15"
rust-ini = "0.14"
typemap = "~0.3"
rand = "~0.7"
failure = "0.1"
tempfile = "3"
graphql_client = "0.8"
serde = "1.0"
serde_json = "1.0"
tokio = "0.2.15"
lazy_static = "1.3"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.7"

[dependencies.sqlx]
version = "0.3.4"
default-features = false
features = ["sqlite", "runtime-tokio", "macros"]

[dependencies.serenity]
git = "https://github.com/Lakelezz/serenity"
branch = "await"
#path = "../serenity"
features = ["framework", "standard_framework", "absolute_ratelimits"]

[dependencies.serenity-lavalink]
git = "https://gitlab.com/nitsuga5124/serenity-lavalink/"
branch = "master"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["rustls-tls", "json"]
