[package]
name = "lupusreginaÎ²"
version = "0.4.4"
authors = ["Ken Swenson <flat@esoteric.moe>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.12.0"
chrono = "0.4.10"
directories = "~2.0"
env_logger = "~0.7"
log = "~0.4"
kankyo = "0.3.0"
rust-ini = "0.14"
rusqlite = "0.21"
typemap = "~0.3"
rand = "~0.7"
failure = "0.1"
tempfile = "3"
graphql_client = "0.8"
serde = "1.0"
serde_json = "1.0"
tokio = "0.2.15"
lazy_static = "1.3"

#[dependencies.sqlx]
#version = "0.3.4"
#default-features = false
#features = ["sqlite", "runtime-tokio"]

[dependencies.serenity]
git = "https://github.com/Lakelezz/serenity"
branch = "await"
#path = "../serenity"
features = ["voice", "framework", "standard_framework", "absolute_ratelimits"]

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["rustls-tls", "json", "blocking"]
